export const changeHomeLang = {
  homeMetaKeywords: {
    en: [
      'immigration law',
      'lawyer',
      'immigration consulting',
      'north carolina',
      'state bar',
      'american immigration lawyers association',
      'aila',
      'tenth judicial district bar',
      'wake county bar association',
      'raleigh',
      'nc',
      'north carolina',
      'justice',
      'equality',
    ],
    es: [
      'ley migratoria',
      'abogado',
      'consultar',
      'barra del estado de Carolina del Norte',
      'asociacion Americana de abogados de migracion',
      'aila',
      'decimo distrito judicial de Carolina del Norte',
      'asociacion de barra del condado de Wake',
      'raleigh',
      'nc',
      'Carolina del Norte',
      'Justicia',
      'Igualdad',
    ],
    ar: [
      'قانون الهجرة',
      'محامي',
      'استشارات قانونية',
      'نقابة محامين ولاية كارولاينا الشمالية',
      'رابطة محاميي الهجرة الأمريكية',
      'aila',
      'عضو في الدائرة القضائية العاشرة',
      'نقابة المحامين في مقاطعة ويك',
      'رالي',
      'nc',
      'نورث كارولاينا',
      'عدالة',
      'مساواة',
    ],
  },
};
