export const changeTeamMembersLang = {
  membersBashiTitle: {
    en: 'Omar Mazin Bashi, Esq. – Owner and Managing Attorney',
    es: 'Omar Mazin Bashi, Esq. - Propietario y Abogado Gerente',
    ar: 'المحامي عمر مازن باشي-المستشار القانوني المؤسس والمدير العام',
  },
  membersBashiParagraph1: {
    en: "Attorney Bashi attended undergrad in Wilson, North Carolina at Barton College; while there he became a member of Sigma Phi Epsilon, and earned his Bachelor of Science Degree with concentrations in Business and Human Resource Management. Following undergrad, Attorney Bashi attended Charlotte School of Law in Charlotte, North Carolina. During his time there, he pursued many volunteer opportunities, one of Attorney Bashi’s favorite experiences volunteering was as a student attorney in the school's immigration clinic. This allowed him to gain vast experience and knowledge in immigration law. Additionally Attorney Bashi completed two Internship programs; the first was with a US Senator, spent learning the inner workings of the US governmental system; and the second was as a case manager for Nexus programs in Fairfax, Virginia, which helped Attorney Bashi gain even more insight and experience in Immigration matters. In 2015 Attorney Bashi received his BAR License shortly after.",
    es: 'El abogado Bashi asistió a la licenciatura en Wilson, Carolina del Norte en Barton College; mientras estuvo allí se convirtió en miembro de Sigma Phi Epsilon y obtuvo su licenciatura en ciencias con especialización en administración de recursos humanos y negocios. Después de graduarse, el abogado Bashi asistió a la Facultad de Derecho de Charlotte en Charlotte, Carolina del Norte. Durante su tiempo allí, buscó muchas oportunidades de voluntariado, una de las experiencias favoritas del abogado Bashi como voluntario fue como estudiante de abogado en la clínica de inmigración de la escuela. Esto le permitió adquirir una vasta experiencia y conocimiento en leyes de inmigración. Además, el abogado Bashi completó dos programas de pasantías; el primero fue con un senador de los Estados Unidos, dedicado a aprender el funcionamiento interno del sistema gubernamental de los Estados Unidos; y el segundo fue como administrador de casos para los programas Nexus en Fairfax, Virginia, lo que ayudó al abogado Bashi a obtener aún más conocimientos y experiencia en asuntos de inmigración. En 2015, el abogado Bashi se graduó de la Facultad de Derecho de Charlotte con su Doctorado en Jurisprudencia y poco después recibió su licencia de BAR.',
    ar: 'المحامي عمر باشي حاصل على درجة البكالوريوس في العلوم مع التخصص في مجال إدارة الاعمال والموارد البشرية من جامعة بارتون في مدينة ويلسون, ولاية كارولاينا الشمالية. شارك المحامي باشي في سيجما فاي إبسيلون كعضو فاعل خلال مدة دراسته الجامعية مما أكسبه الكثير من الخبرات والمهارات. بعد حصوله على شهادة البكالوريوس انضم المحامي باشي الى كلية شارلوت للدراسات القانونية في مدينة شارلوت, ولاية كارولاينا الشمالية. بالإضافة الى مشاركاته المتنوعة في العديد من الفرق والمنظمات التطوعية خلال فترة تواجده في مدينة شارلوت. كما أن تجربة مشاركته في مركز الهجرة الجامعي كطالب محامي تعد من أهم وأفضل التجارب التي اكسبت المحامي باشي العديد من القدرات والخبرات في القضايا المتعلقة بشؤون الهجرة. علاوة على ذالك فقد شارك المحامي باشي في برنامجين للتدريب المتخصص والذين اسهما في صقل معارفه وتطويرها, كان برنامج التدريب الاول مع عضو في مجلس الشيوخ الأمريكي بهدف تعلم وإتقان الية عمل النظام الداخلي في الحكومة الأمريكية إضافة إلى البرنامج الثاني الذي عمل فيه كمدير متابع في برنامج نيكسوس في مدينة فيرفاكس, ولاية فيرجينيا وقد ساهم هذا البرنامج في إكساب المحامي باشي خبرة أعمق وأدق في قضايا الهجرة. تخرج المحامي باشي من جامعة شارلوت للدراسات القانونية في عام ٢٠١٥ بعد حصولة على شهادة الدكتوراة في القانون وحصل بعدها بفترة وجيزة على شهادة مزاولة مهنة المحاماة بعد انضمامه الى نقابة المحامين في ولاية كارولاينا الشمالية',
  },
  membersBashiParagraph2: {
    en: 'In 2018, attorney Bashi decided it was time to own and manage his own law firm at which point he established Bashi Law, PLLC in Raleigh, North Carolina. Prior to opening up Bashi Law, Attorney Bashi was employed as an associate attorney at Guirguis Law; where he represented a wide variety of clients in all types of immigration matters; including, but not limited to Asylum and family-based claims. After leaving Guirguis Law, Attorney Bashi was employed as the lead of immigration cases.',
    es: 'En 2018, el abogado Bashi decidió que era hora de poseer y administrar su propio bufete de abogados, momento en el que estableció Bashi Law, PLLC en Raleigh, Carolina del Norte. Antes de abrir Bashi Law, el abogado Bashi trabajó como abogado asociado en Guirguis Law; donde representó a una amplia variedad de clientes en todo tipo de asuntos migratorios; incluyendo, pero no limitado a, asilo y solicitudes basadas en la familia. Después de dejar Guirguis Law, el abogado Bashi fue contratado como abogado asociado principal de Arenas Immigration, donde manejó una variedad de casos de inmigración.',
    ar: 'في العام ٢٠١٨ قرر المحامي باشي تأسيس مكتب استشارات قانونية خاص به في مدينة رالي,ولاية كارولاينا الشمالية تحت إشرافه الشخصي فكان ذالك حجر الاساس لتاسيس شركة باشي للمحاماة والإستشارات القانونية. شغل المحامي باشي عدة مناصب مفصلية في مجال العمل القانوني قبل إنشائه لمكتب الاستشارات القانونية. فقد شغل منصب محامي مساعد في شركة جرجس لو للإستشارات القانونية حيث قام بالعمل مع شريحة واسعة ومتنوعة من العملاء في مسائل الهجرة واللجوء ولم الشمل العائلي التي زرعت فيه جوهر العمل القانوني. كما عمل المحامي باشي كمحامي مشارك في مكتب اريناس لشؤون الهجرة حيث تولى الاشراف على العديد من قضايا الهجرة.',
  },
  membersBashiParagraph3: {
    en: 'As a Naturalized U.S. Citizen, Attorney Bashi understands the struggle and the importance of obtaining legal status in the United States. As such, he helps his clients navigate the ever-changing immigration world, while providing proper and detailed representation to them. Attorney Bashi’s career has been greatly dedicated toward his passion of helping others obtain legal status in the United States, and to live the American Dream. Currently, Attorney Bashi takes immigration cases in all US States, and handles traffic violations and minor traffic misdemeanors within the State of North Carolina.',
    es: 'Como ciudadano estadounidense naturalizado, el abogado Bashi comprende la lucha y la importancia de obtener un estatus legal en los Estados Unidos. Como tal, ayuda a sus clientes a navegar por el mundo de la inmigración en constante cambio, mientras les brinda una representación adecuada y detallada. La carrera del abogado Bashi se ha dedicado en gran medida a su pasión por ayudar a otros a obtener un estatus legal en los Estados Unidos y vivir el Sueño Americano. Actualmente, el abogado Bashi se ocupa de casos de inmigración en todos los estados de los EE. UU. Y se ocupa de las infracciones de tránsito y los delitos menores de tránsito dentro del estado de Carolina del Norte.',
    ar: 'ينظرالمحامي باشي بقلب متعاطف وعقل واعي الى المعاناة الكبيرة التي يمر بها المهاجرون في رحلة قدومهم الى الولايات المتحدة ويقدر تماما أهمية حصول المهاجرين على صفة ووثائق قانونية تمكنهم من العيش في الولايات المتحدة الأمريكية كأي مواطن أمريكي. ولذالك فقد عقد المحامي باشي العزم على مد يد العون والمساعدة وتوفير التمثيل القانوني الأفضل لكل المهاجرين وعائلاتهم في عالم الهجرة المتغير باستمرار. اتخذ المحامي باشي مهنة المحاماة بسبب شغفه الكبير في مساعدة المهاجرين كواجب إنساني أولاً و للحصول على وضع قانوني سليم في الولايات المتحدة ثانيا كخطوة أولى وأساسية على طريق الحلم الأمريكي. حاليا يتولى المحامي باشي قضايا الهجرة في مختلف الولايات الامريكية كما انه يتولى القضايا المتعلقة بالمخالفات المرورية وقضايا الجنح داخل ولاية كارولاينا الشمالية.',
  },
  membersCynthTitle: {
    en: 'Cynthia Martinez – Lead Paralegal',
    es: 'Cynthia Martinez - Paralegal Prinicipal',
    ar: 'سينثيا مارتينيز - مساعدة في الشؤون القانونية',
  },
  membersCynthParagraph1: {
    en: 'Cynthia Martinez was born in Nuevo Leon, Mexico, the middle child of three. She immigrated to the United States with her family when she was two. Her parents instilled upon her a love for knowledge, all types of knowledge. In 2011, Ms. Martinez got involved with the NC Dream Team and through her activism committed acts of civil disobedience in Charlotte, NC and then again in 2012 at the NC General Assembly.',
    es: 'Cynthia Martinez nació en Nuevo León, México. Emigró a los Estados Unidos con su familia cuando tenía dos años. Sus padres le inculcaron el amor por el conocimiento, todo tipo de conocimiento. En 2011, la Sra. Martínez se involucró con el NC Dream Team y a través de su activismo cometió actos de desobediencia civil en Charlotte, Carolina del Norte y luego nuevamente en 2012 en la Asamblea General de Carolina del Norte.',
    ar: 'ولدت سينثيا مارتينيز في نويفو ليون ، المكسيك ، وهي الطفلة الأوسط لعائلة مكونة من ثلاثة اطفال. هاجرت سينثيا الى الولايات المتحدة مع عائلتها عندما كانت بعمر السنتين وبدأت مسيرتها على طريق الحلم الأمريكي مستفيدة من والديها الذان غرسا فيها العديد من القيم والمبادئ. في عام ٢٠١١ انخرطت السيدة مارتينز مع فريق ان سي دريم الذي أكسبها العديد من المهارات كما أنها شاركت بالعديد من المنظمات والفعاليات المدنية في مدينة شارلوت مكتسبة بذالك خبرة واسعة في مجال العمل الإنساني علاوة على مشاركتها المميزة في الجمعية العامة لولاية كارولاينا الشمالية في العام ٢٠١٢',
  },
  membersCynthParagraph2: {
    en: "Ms. Martinez discovered her passion for law after working in her first legal position. Her fervor only grew, after joining another firm in 2014, where she spent a lot of time learning about the Federal Justice system. Ms. Martinez found that she excelled in learning how the system worked, primarily in the Eastern District of North Carolina; and was mentored by an exceptionally intelligent attorney, who also instilled in her a thirst for knowledge and a conviction in always finding a way to help clients. After many trials and tribulations, as well as a mass amount of learning and experiences, Ms. Martinez left that office in 2019 with a wealth of knowledge under her belt. Shortly after, Ms. Martinez began employment with a nonprofit organization that has a rapid response system for people detained at Jackson Parish, LA. It was here, that Ms. Martinez heard the terrifying stories of many individuals, and how they were fleeing from: violence, death threats, sexual exploitations, and many other horrors at the hands of other people in their home countries. Under the guidance of an attorney, Ms. Martinez was able to successfully assist a Nicaraguan national seeking political asylum in this country, win his case, and be allowed refuge in this country. It was one of Ms. Martinez's most proud moments. Ms. Martinez currently works as a paralegal at Bashi Law, PLLC.",
    es: 'La Sra. Martínez descubrió su pasión por la ley después de trabajar en su primer puesto legal. Su fervor solo creció, después de unirse a otra firma en 2014, donde pasó mucho tiempo aprendiendo sobre el sistema de justicia federal. La Sra. Martínez descubrió que se destacó al aprender cómo funcionaba el sistema, principalmente en el Distrito Este de Carolina del Norte; y fue asesorada por una abogada excepcionalmente inteligente, quien también le inculcó una sed de conocimiento y la convicción de encontrar siempre la manera de ayudar a los clientes. Después de muchas pruebas y tribulaciones, así como una gran cantidad de aprendizaje y experiencias, la Sra. Martínez dejó esa oficina en 2019 con una gran cantidad de conocimientos en su haber. Poco después, la Sra. Martínez comenzó a trabajar en una organización sin fines de lucro que tiene un sistema de respuesta rápida para las personas detenidas en Jackson Parish, LA. Fue aquí donde la Sra. Martínez escuchó las aterradoras historias de muchas personas y de cómo estaban huyendo: violencia, amenazas de muerte, explotación sexual y muchos otros horrores a manos de otras personas en sus países de origen. Bajo la dirección de un abogado, la Sra. Martínez pudo ayudar con éxito a un ciudadano nicaragüense que buscaba asilo político en este país, ganar su caso y obtener refugio en este país. Fue uno de los momentos más orgullosos de la Sra. Martínez. La Sra. Martínez trabaja actualmente como asistente legal en Bashi Law, PLLC.',
    ar: 'اكتشفت السيدة مارتينز شغفها بالعمل القانوني منذ وقت مبكر وخصوصاً بعد توليها لمنصبها القانوني الأول الذي ساهم في تنمية شغفها للعمل القانوني بشدة.و بعد انضمامها لشركة استشارات قانونية في العام ٢٠١٤ أمضت السيدة مارتينز الكثير من الوقت في تعلم نظام العدالة الفدرالي للاستفادة منه في مجال اختصاصها.اظهرت السيدة مارتينز اتقاناً فريداً من نوعه في فهم كيفية عمل النظام القانوني وخصوصا في المقاطعة الشرقية لولاية كارولاينا الشمالية واتمت السيدة مارتينز تدريبها على يد أمهر المحاميين الذين غرسوا فيها حبها للمعرفة وتصميمها الدائم لإيجاد طريقة لمساعدة عملائها. بعد تجاوزها للعديد من المصاعب والمحن والتي اكسبتها خبرة واسعة في مجال عملها قررت السيدة مارتيز في عام ٢٠١٩ مغادرة المكتب الذي تعمل به بعد تحقيقها العديد من النجاحات في المجال القانوني. بعد ذالك بفترة وجيزة بدأت السيدة مارتيز بالعمل مع منظمة غير ربحية تهدف للدفاع عن المحتجزين في منطقة جاكسون باريش، ولاية لوس انجلوس خلال عملها هناك سمعت السيدة مارتيز العديد من القصص المأساوية لأشخاص عانو من العنف والتهديد بالموت والإستغلال الجنسي والعديد من الماسي الاخرى التي تعرضوا لها من قبل أشخاص في بلدانهم الاصلية. ولعل من أفضل لحظات مسيرة السيدة مارتينز المهنية هي حين تمكنت من مساعدة مواطن من نيكاراغوا بالحصول على اللجوء السياسي في الولايات المتحدة وتعتبر اليسدة مارتينز هذه اللحظة من أهم ذكرياتها على الصعيدين الشخصي والعملي. الأن تعمل السيدة مارتيز كمحامية في مكتب باشي للاستشارات القانونية',
  },
};
